services:
  iSponsorBlockTV:
    container_name: iSponsorBlockTV

    image: ghcr.io/dmunozv04/isponsorblocktv

    pull_policy: build
    
    restart: unless-stopped

    network_mode: bridge
    
    volumes:
    - /appdata/isponsorblocktv:/app/data
