# Needed environment variables:
# - OVERSEER_HOST: The hostname of the service.

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
      - PORT=5055 #optional
    volumes:
      - /appdata/overseer:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseer.rule=Host(`${OVERSEER_HOST}`)"
      - "traefik.http.routers.overseer.entrypoints=websecure"
      - "traefik.http.routers.overseer.tls.certresolver=cloudflare"
    networks:
      - tunnel
      - proxy
    restart: unless-stopped
    pull_policy: build

networks:
  tunnel:
    external: true
  proxy:
    external: true
