services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    volumes:
      - /appdata/overseer:/app/config
    network_mode: bridge
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
      - PORT=5055 #optional
    restart: unless-stopped
    pull_policy: build
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.rule=Host(`overseer.iscariot.nervhq.io`)"
      - "traefik.http.routers.uptimekuma.entrypoints=websecure"
      - "traefik.http.routers.uptimekuma.tls.certresolver=cloudflare"
