# Needed environment variables:
# - OVERSEER_HOST: The hostname of the service.
services:
  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    pull_policy: build
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
    networks:
      - proxy
    volumes:
      - /appdata/overseer:/app/config
    labels:
      - traefik.enable=true
      - "traefik.http.routers.overseer.rule=Host(`${OVERSEER_HOST}`)"
      - traefik.http.routers.overseer.entrypoints=websecure
      - traefik.http.routers.overseer.tls.certresolver=cloudflare
networks:
  proxy:
    external: true
