version: "3.8"

services:
  caddy:
    image: jmdarling0/caddy-cloudflare:latest
    restart: unless-stopped
    pull_policy: build
    environment:
      CLOUDFLARE_AUTH_TOKEN: ${CLOUDFLARE_AUTH_TOKEN}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /etc/caddy:/etc/caddy
      - ./daddy-data:/data
      - ./caddy-config:/config
