version: '3.8'

services:
  caddy:
    image: jmdarling0/caddy-cloudflare:latest
    restart: unless-stopped
    pull_policy: build
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
