# Needed environment variables:
#  - CF_API_EMAIL: Your Cloudflare account email.
#  - CF_DNS_API_TOKEN: Your Cloudflare API token.
services:
  traefik:
    container_name: traefik
    image: traefik:v3.2
    restart: unless-stopped
    command:
      - --accesslog=true
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - "--certificatesresolvers.cloudflare.acme.email=${CF_API_EMAIL}"
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --log.level=DEBUG
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-appdata:/letsencrypt
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  proxy:
    driver: bridge
    name: proxy
volumes:
  traefik-appdata:
