# Needed environment variables:
# OPEN_WEB_UI_HOST - The URL at which this service should be made available.
services:
  open-web-ui:
    container_name: open-web-ui
    image: ghcr.io/open-webui/open-webui:main
    pull_policy: build
    restart: unless-stopped
    networks:
      - proxy
      - tunnel
    volumes:
      - open-web-ui:/app/backend/data
    labels:
      - traefik.enable=true
      - "traefik.http.routers.openwebui.rule=Host(`${OPEN_WEB_UI_HOST}`)"
      - traefik.http.routers.openwebui.entrypoints=websecure
      - traefik.http.routers.openwebui.tls.certresolver=cloudflare
networks:
  proxy:
    external: true
  tunnel:
    external: true
volumes:
  open-web-ui:

