services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    pull_policy: build
    restart: unless-stopped
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
