# Needed environment variables:
# IMMICH_DB_PASSWORD = password for database

services:
  immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:release
    depends_on:
      - immich-cache
      - immich-database
    pull_policy: build
    restart: unless-stopped
    network_mode: bridge
    ports:
      - '2283:2283'
    volumes:
      - /mnt/lilin/media/images/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`immich.iscariot.nervhq.io`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls.certresolver=cloudflare"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    pull_policy: build
    restart: unless-stopped
    volumes:
      - immich-model-cache:/cache

  immich-cache:
    container_name: immich-cache
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    pull_policy: build
    restart: unless-stopped

  immich-database:
    container_name: immich-database
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    pull_policy: build
    restart: unless-stopped
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    environment:
      POSTGRES_DB: 'immich'
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: 'immich'
    volumes:
      - /appdata/immich/database/postgres:/var/lib/postgresql/data

volumes:
  immich-model-cache:
