# Needed environment variables:
# ATUIN_HOST - The URL at which this service should be made available.
services:
  atuin:
    container_name: atuin
    image: ghcr.io/atuinsh/atuin:v18.7.1
    pull_policy: build
    user: 2000:2000
    restart: unless-stopped
    command: server start
    environment:
      - ATUIN_HOST=0.0.0.0
      - ATUIN_PORT=8888
      - ATUIN_DB_URI=sqlite:///config/atuin.db
      - ATUIN_OPEN_REGISTRATION=true
    networks:
      - proxy
    volumes:
      - /opt/appdata/atuin/config:/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - "traefik.http.routers.atuin.rule=Host(`${ATUIN_HOST}`)"
      - traefik.http.routers.atuin.entrypoints=websecure
      - traefik.http.routers.atuin.tls.certresolver=cloudflare
      - traefik.http.services.atuin.loadbalancer.server.port=8888
networks:
  proxy:
    external: true