# Needed environment variables:
#  - TUNNEL_TOKEN: The token for the Cloudflare tunnel.

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command:
      - "tunnel"
      - "--no-autoupdate"
      - "run"
    networks:
      - tunnel
    restart: unless-stopped
    pull_policy: build

networks:
  tunnel:
    name: tunnel
    driver: bridge
