services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    network_mode: bridge
    command:
      - "tunnel"
      - "--no-autoupdate"
      - "run"
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    pull_policy: build
      
