# Needed environment variables:
#  - TUNNEL_TOKEN: The token for the Cloudflare tunnel.

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - tunnel
    pull_policy: build

networks:
  tunnel:
    name: tunnel
    driver: bridge
