# Needed environment variables:
#  - TUNNEL_TOKEN: The token for the Cloudflare tunnel.
services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    pull_policy: build
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - tunnel
networks:
  tunnel:
    name: tunnel
    driver: bridge
