# Needed environment variables:
# PORTAINER_HOST - The URL at which this service should be made available.
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.31.3
    restart: always
    command: -H unix:///var/run/docker.sock
    networks:
      - proxy
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOST}`)"
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls.certresolver=cloudflare
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.services.portainer.loadbalancer.server.scheme=http
networks:
  proxy:
    external: true
volumes:
  portainer_data:

