services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    runtime: nvidia
    ports:
      - "11434:11434"
    volumes:
      - ollama-appdata:/root/.ollama
volumes:
  ollama-appdata:
