# Needed environment variables:
#  - UPTIME_KUMA_HOST: The hostname of the service.
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    pull_policy: build
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /appdata/uptime-kuma:/app/data
    labels:
      - traefik.enable=true
      - "traefik.http.routers.uptimekuma.rule=Host(`${UPTIME_KUMA_HOST}`)"
      - traefik.http.routers.uptimekuma.entrypoints=websecure
      - traefik.http.routers.uptimekuma.tls.certresolver=cloudflare

networks:
  proxy:
    external: true
