# Needed environment variables:
#  - HOSTNAME: The hostname of the service.

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - 3001:3001
    volumes:
      - /appdata/uptime-kuma:/app/data
    networks:
      - proxy
    restart: unless-stopped
    pull_policy: build
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.uptimekuma.entrypoints=websecure"
      - "traefik.http.routers.uptimekuma.tls.certresolver=cloudflare"

networks:
  proxy:
    external: true
