services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /appdata/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    pull_policy: build
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.rule=Host(`uptime-kuma.iscariot.nervhq.io`)"
      - "traefik.http.routers.uptimekuma.entrypoints=web"
