# Needed environment variables:
# DASHY_HOST - The URL at which this service should be made available.
services:
  dashy:
    container_name: dashy
    image: lissy93/dashy
    pull_policy: build
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - proxy
    volumes:
      - /appdata/dashy:/app/user-data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - "traefik.http.routers.dashy.rule=Host(`${DASHY_HOST}`)"
      - traefik.http.routers.dashy.entrypoints=websecure
      - traefik.http.routers.dashy.tls.certresolver=cloudflare
networks:
  proxy:
    external: true
