# Needed environment variables:
# GLANCE_HOST - The URL at which this service should be made available.
services:
  glance:
    container_name: glance
    image: glanceapp/glance
    pull_policy: build
    restart: unless-stopped
    networks:
      - proxy
      - tunnel
    volumes:
      - /appdata/glance:/app/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - "traefik.http.routers.glance.rule=Host(`${GLANCE_HOST}`)"
      - traefik.http.routers.glance.entrypoints=websecure
      - traefik.http.routers.glance.tls.certresolver=cloudflare
      - traefik.http.routers.glance.middlewares=tinyauth
networks:
  proxy:
    external: true
  tunnel:
    external: true
