# Needed environment variables:
# MANYFOLD_SECRET_KEY_BASE - Base to use for secret key generation.

services:
  manyfold:
    container_name: manyfold

    image: ghcr.io/manyfold3d/manyfold-solo:latest

    pull_policy: build

    restart: unless-stopped

    environment:
      SECRET_KEY_BASE: ${MANYFOLD_SECRET_KEY_BASE}
      PUID: 1000
      PGID: 1000

    network_mode: bridge

    ports:
      - 3214:3214

    volumes:
      - /appdata/manyfold/config:/config
      - /mnt/lilin/resources/3d-models:/libraries

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.manyfold.rule=Host(`manyfold.iscariot.nervhq.io`)"
      - "traefik.http.routers.manyfold.entrypoints=websecure"
      - "traefik.http.routers.manyfold.tls.certresolver=cloudflare"
